[components.run]

[components.run.celestia]
about = "Run Celestia orbit"

[components.run.celestia.light]
about = "Run Celestia light node"
binary = "/tmp/orb/celestia/celestia"
download = "~/orb-p/scripts/run/celestia.sh"

[components.run.celestia.bridge]
about = "Run Celestia bridge node"
binary = "/tmp/orb/celestia/celestia"
download = "/tmp/orb/celestia/init.sh"

[components.run.avail]
about = "Run Avail orbit"

[components.run.avail.light]
about = "Run Avail light node"
binary = "avail-light"
download = "/tmp/orb/avail/init.sh"


