[components.run]

[components.run.celestia]
about = "Run Celestia orbit"

[components.run.celestia.light]
about = "Run Celestia light node"
binary = "celestia-light"
download = "~/.orb/scripts/run/celestia.sh"

[components.run.celestia.bridge]
about = "Run Celestia bridge node"
binary = "celestia-bridge"
download = "~/.orb/scripts/run/celestia.sh"


[components.run.avail]
about = "Run Avail orbit"

[components.run.avail.light]
about = "Run Avail light node"
binary = "orb-avail-light"
download = "~/.orb/scripts/run/avail.sh"

[components.run.avail.full]
about = "Run Avail full node"
binary = "orb-avail-full"
download = "~/.orb/scripts/run/avail-full.sh"


[components.run.rollkit]
about = "Run Rollkit orbits"

[components.run.rollkit.avail]
about = "Run Rollkit avail nodes"
binary = "orb-rollkit-avail"
download = "~/.orb/scripts/run/rollkit_avail.sh"

[components.run.rollkit.gmd-avail]
about = "Run Rollkit gmd node"
binary = "orb-rollkit-gmd"
download = "~/.orb/scripts/run/rollkit_gmd.sh"

[components.run.rollkit.celestia]
about = "Run Rollkit celestia node"
binary = "orb-rollkit-avail"
download = "~/.orb/scripts/run/rollkit_celestia.sh"

[components.run.rollkit.gmd-celestia]
about = "Run Rollkit gmd nodes"
binary = "orb-rollkit-gmd"
download = "~/.orb/scripts/run/rollkit_gmd_celestia.sh"