[components.run]

[components.run.celestia]
about = "Run Celestia orbit"

[components.run.celestia.light]
about = "Run Celestia light node"
binary = "celestia-light"
download = "~/.orb/scripts/run/celestia.sh"

[components.run.celestia.bridge]
about = "Run Celestia bridge node"
binary = "celestia-bridge"
download = "~/.orb/scripts/run/celestia.sh"

[components.run.avail]
about = "Run Avail orbit"

[components.run.avail.light]
about = "Run Avail light node"
binary = "orb-avail-light"
download = "~/.orb/scripts/run/avail.sh"


[components.run.avail.full]
about = "Run Avail full node"
binary = "orb-avail-full"
# download = "~/.orb/scripts/run/avail-full.sh"
download = "~/orb/scripts/run/avail-full.sh"